AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16  #Out of 200 only 16 images will be processed in one go , then next 16 will arrive and so on....
INCLUDE_TOP: False 
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01